### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by eugenioghio** [dpa99c/cordova-plugin-androidx#1]
**I'm submitting a ...**  (check one with "x"):
- [ x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

when I tried to add the platform android to my ionic project I got: 

> Cannot find plugin.xml for plugin "cordova-plugin-androidx". Please try adding it again.

I try to reinstall androidx:
`cordova plugin add cordova-plugin-androidx`
I get: 

> Cannot find plugin.xml for plugin "cordova-plugin-androidx". Please try adding it again.

I try to remove androidx:
`cordova plugin rm cordova-plugin-androidx`
I get 

> Cannot find plugin.xml for plugin "cordova-plugin-androidx". Please try adding it again.

**Expected behavior:**

Be able to either ad or remove the plugin

**Steps to reproduce:**

`cordova plugin add cordova-plugin-androidx`
`cordova plugin rm cordova-plugin-androidx`

**Environment information**

- Cordova CLI version 
	9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- Available platforms:
       
>  android ^8.0.0
>  browser ^6.0.0
>  electron ^1.0.0
>  ios ^5.0.0
>  osx ^5.0.0
>  windows ^7.0.0

- Plugins & versions installed in project (including this plugin)
 

> cordova-android-support-gradle-release 2.1.0 "cordova-android-support-gradle-release"
> cordova-clipboard 1.2.1 "Clipboard"
> cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
> cordova-plugin-android-permissions 1.0.0 "Permissions"
> cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
> cordova-plugin-app-version 0.1.9 "AppVersion"
> cordova-plugin-device 2.0.2 "Device"
> cordova-plugin-document-viewer 0.9.10 "SitewaertsDocumentViewer"
> cordova-plugin-file 6.0.1 "File"
> cordova-plugin-file-opener2 2.2.0 "File Opener2"
> cordova-plugin-file-transfer 1.7.1 "File Transfer"
> cordova-plugin-firebasex 5.0.0 "Google Firebase Plugin"
> cordova-plugin-geolocation 4.0.1 "Geolocation"
> cordova-plugin-ionic 5.3.0 "cordova-plugin-ionic"
> cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
> cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
> cordova-plugin-nativegeocoder 3.2.1 "NativeGeocoder"
> cordova-plugin-network-information 2.0.1 "Network Information"
> cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
> cordova-plugin-splashscreen 5.0.2 "Splashscreen"
> cordova-plugin-statusbar 2.4.2 "StatusBar"
> cordova-plugin-whitelist 1.3.3 "Whitelist"
> cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
> cordova.plugins.diagnostic 4.0.12 "Diagnostic"
> es6-promise-plugin 4.1.0 "Promise"
> phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
> wifiwizard2 3.1.1 "WifiWizard2"

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `1903`
    
Android SDK Tools : 26.1.1 (C:\sdk-tools)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
  

>   Ionic CLI                     : 5.1.0 (C:\Users\PROGETTO\AppData\Roaming\npm\node_modules\ionic)
>    Ionic Framework               : @ionic/angular 4.6.2
>    @angular-devkit/build-angular : 0.13.9
>    @angular-devkit/schematics    : 7.2.4
>    @angular/cli                  : 7.3.9
>    @ionic/angular-toolkit        : 1.4.1

**Comment by dpa99c** [comment]
> Cannot find plugin.xml for plugin "cordova-plugin-androidx". Please try adding it again.

This happens when Cordova fails to install a plugin completely but is not caused by this plugin itself.
