### ISSUE TITLE
This repository can now be archived as cordova-android now has inbuilt support for AndroidX

### ISSUE THREAD

**Issue by sagrawal31** [dpa99c/cordova-plugin-androidx#5]
# Documentation issue

https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html
![image](https://user-images.githubusercontent.com/1804514/89482432-834bee80-d7b7-11ea-81c8-ec013f687721.png)

It is proud to see that Cordova has referenced this plugin in their blog post. But like mentioned, since `cordova-android > 9.0.0`, this plugin is no longer needed. So the following changes can be done in this repo-

1. Update README.md to mark the required `cordova-android` version < 9.0.0.
2. Archive the repository.

**THANKS FOR YOUR CONTRIBUTION TOWARDS THE CORDOVA COMMUNITY**  👏

**Comment by mst2020** [comment]
Hello,

if a user upgrades to cordova-android 9 , he **must** uninstall this plugin, because now this plugin floods the gradle.properties file:
```
android.enableJetifier=false
android.useAndroidX=false
android.enableJetifier=false
android.useAndroidX=false
android.enableJetifier=false
android.useAndroidX=false
android.enableJetifier=false
android.useAndroidX=false
android.enableJetifier=false
android.useAndroidX=false
android.enableJetifier=false
android.useAndroidX=false
android.enableJetifier=false
android.useAndroidX=false
android.enableJetifier=false
android.useAndroidX=false
android.enableJetifier=false
android.useAndroidX=false
android.enableJetifier=false
android.useAndroidX=false
android.enableJetifier=false
android.useAndroidX=true
android.enableJetifier=true
```
cordova-android 9.0.0 & cordova-plugin-androidx 2.0.0

With each build it adds two lines, i'm now at 12744 :dancers: :)

Just sayin.

Thanks & good night :)

**Comment by dpa99c** [comment]
The engine constraint [has been updated](https://github.com/dpa99c/cordova-plugin-androidx/commit/f51f4f397bb3c2bf31fd89d1473b309c8eb19300) to make the plugin specific to `cordova-android@<=8` and the plugin documentation [has been updated](https://github.com/dpa99c/cordova-plugin-androidx/commit/856c25b31437b0124147df4c403244cc2cd150dc) to notify of plugin deprecation

**Comment by sagrawal31** [comment]
Thanks @dpa99c

**Comment by sagrawal31** [comment]
Do you mind achieving this project as developer tend to catch that "Archived banner" quickly rather than reading the bold Deprecation notice?
